version: '3'

services:
  tester:
    build: .
    container_name: tester
    environment:
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
    ports:
      - "8080:8080"
    depends_on:
      - jaeger
  jaeger:
    container_name: jaeger_all_in_one
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"