openapi: 3.0.1
info:
  title: cm-go-service
  description: ""
  version: 0.0.1
servers:
- url: https://api.ft.com/
paths:
  /test:
    get:
      summary: Test
      description: This is just a test endpoint.
      responses:
        200:
          description: Should always return 200
          content: {}
  /__health:
    get:
      summary: Healthchecks
      description: Runs application healthchecks and returns FT Healthcheck style
        json.
      responses:
        200:
          description: Should always return 200 along with the output of the healthchecks
            - regardless of whether the healthchecks failed or not. Please inspect
            the overall `ok` property to see whether or not the application is healthy.
          content: {}
  /__build-info:
    get:
      summary: Build Information
      description: Returns application build info, such as the git repository and
        revision, the golang version it was built with, and the app release version.
      responses:
        200:
          description: Outputs build information as described in the summary.
          content:
            application/json; charset=UTF-8:
              example:
                version: 0.0.1
                repository: https://github.com/Financial-Times/cm-go-service.git
                revision: 7cdbdb18b4a518eef3ebb1b545fc124612f9d7cd
                builder: go version go1.14 linux/amd64
                dateTime: "20161123122615"
  /__gtg:
    get:
      summary: Good To Go
      description: Lightly healthchecks the application, and returns a 200 if it's
        Good-To-Go.
      responses:
        200:
          description: The application is healthy enough to perform all its functions
            correctly - i.e. good to go.
          content: {}
        503:
          description: One or more of the applications healthchecks have failed, so
            please do not use the app. See the /__health endpoint for more detailed
            information.
          content: {}
components: {}
